### PR TITLE
Fix URLs in the help menu & make package/folder names consistent with Pale Moon

### PR DESCRIPTION
**Pull request by trav90**

### CODE REVIEW

**Comment by wolfbeast** [comment]
Hey, thanks for your suggestion but the "support baseurl" can't point to the forum that way. it will have specific entries appended depending on which help function is called in the client. I don't have anything set up for that, since it will require specific pages or redirects in place for the individual functions. Is this broken on the Mozilla side or something?

As for APPNAME... why is capitalization a problem?

**Comment by trav90** [comment]
Just curious, which individual functions are you referring to? The Help Contents (F1) from the menu was the only one I was aware of. It currently points to the Mozilla Thunderbird online help, but I though it might be good to point it to the FM forum section for support.

As for APPNAME, it is not a problem, but rather a request from a user (since Pale Moon builds use a lowercase named package and folder, they asked if FossaMail could as well for consistency).

**Comment by wolfbeast** [comment]
The baseurl is used by all help functions that link to an external page. Help, F1, Help buttons in the preferences for different pages, etc. etc.
It will append a specific suffix to the base (hence the name) to call up specific individual pages on the website indicated by baseurl. The resulting URL on the forum would not make much sense as a result...

**Comment by wolfbeast** [comment]
As for the package name... I guess people don't like mixed case file names on Linux (on Windows it doesn't matter but it looks better). Drawback of a case-sensitive file system...

**Comment by trav90** [comment]
Gotcha, I didn't even think about help buttons in preferences, etc. I was fixing the URL for the release notes in the help menu, and got a wild hair to update the help contents URL while I was at it! :)

**Comment by trav90** [comment]
The appname isn't really an issue (obviously since people have been using it); I personally think that it looks better mixed case on Linux too. Like I said it was just a request from someone who preferred it being consistent with Pale Moon (all lowercase). It really just comes down to personal preference. If you'd rather leave it as-is, let me know and I'll revert that commit as well. At least one of my 3 changes would still apply. ;)

**Comment by trav90** [comment]
Something I just thought of regarding the appname: If we change it to lowercase, when the user extracts the package, it will not automatically overwrite the previous version (and any menu entries that may have been created would still point to the previous version as well), which could potentially confuse some users. That would definitly have to be stated somewhere, and hopefully people would read before installing. May be more trouble then it is worth.

**Comment by wolfbeast** [comment]
Well, actually, the releasenotes URL is already covered too, since it's picked up from the branding prefs... The only thing done would be to ALSO list it in the branding-independent configuration file instead of using the Thunderbird ref, which would be applicable if someone else builds it from source without official branding. To do it properly it'd have to be rebranded in all config files and make it unified if the link with Thunderbird should be removed. 

So.. really, just going to close this pull request for now. It needs something a bit more encompassing and structural to do it properly.

**Comment by trav90** [comment]
The URL for the release notes is already correct in the mail/branding/(un)official/thunderbird-branding.js, but when selecting the release notes from the help menu in 25.1.2, the following URL opens (resulting in a 404 not found error):

http://live.mozillamessaging.com/fossamail/releasenotes?locale=en-US&version=25.1.2&os=Linux&buildid=20150323155209

Not trying to be a pest, just trying to learn something.

**Comment by wolfbeast** [comment]
Stupid thunderbird pref order being messed up again... :P
Well there may not be a choice then but to hardcode it.

**Comment by trav90** [comment]
I did a search for "app.releaseNotesURL" throught the code, and I didn't find any other location where it was mentioned. I even did a search for the same in the current Thunderbird source code, but the only additional places it came up was in locations not applicable to FossaMail (eg. suite/, mobile/). What should I be looking for?

(I also reverted the lowercase appname patch. If/when we get the release notes URL hammered out, I can delete my repo and re-fork it to make a new pull request without all the "baggage" of the extra commits and reverts if you want.)

**Comment by trav90** [comment]
Closing the pull request, since this was fixed in commit 63ba176

**Comment by wolfbeast** [comment]
Yeah sorry, just manually did this.

**Pull request closed without merging**
